name: update

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      version:
        type: string
      assets:
        type: string
      mock:
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: 'temp'
    - name: Copy public
      run: cp -r ./public/* ./temp
    - name: Genetare update files
      env:
        MOCK: ${{ inputs.mock }}
        NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
        ASSETS: ${{ inputs.assets }}
      run: node ./scripts/update.mjs
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: temp
        clean: false
